---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages(c("arules", "arulesViz"))

library(arules)
library(arulesViz)
library(tidyverse)
library(haven)
library(data.table)
```


## the BKL study

Technical, Mathematical, Artistic, Computer, Cognitive, Managerial, Interpersonal, Self-organization, Physical, Availability, Office

Link to description of the study (in English) -- https://arxiv.org/abs/1908.06731

```{r}
bkl <- readRDS("../data/data-bkl.rds")
```


1. Convert data.frame to matrix / sparse Matrix (e.g. Matrix package)
2. Then use `as()` function
```{r}
dane_arules_m <- as.matrix(bkl)
skills <- as(dane_arules_m, "transactions")
skills
```


```{r}
summary(skills)
```


3. apriori algorithm

```{r}
result <- apriori(skills)
```

4. inspect

```{r}
inspect(result)
```

5. Visualise results

```{r}
arulesViz::ruleExplorer(result)
```

```{r}
arulesViz::inspectDT(result)
```


How to specify your own defaults

```{r}
rules_custom <- apriori(data = skills, parameter = list(support = 0.2, confidence  = 0.7))
inspect(rules_custom)
```

